### ISSUE TITLE
Support map server

### ISSUE THREAD

**Issue by robertwil** [boschglobal/locator_ros_bridge#2]
Hi,
we've recently bought the bosch locator software and would like to extend the existing locator_ros_bridge to also support the map server.
To not waste time I would like to coordinate this development. 
It would be nice if you could explain, whether you've already started with its implementation (and how far it is) or -if not- if you've already thought about the future structure of the code.

Best regards
Robert

**Comment by slaible** [comment]
Hi @robertwil,

Thank you for your request and sorry for the late answer due to vacation. There are currently no plans to also support the server. So feel free to extend the bridge.  I think, a straight-forward approach would be to add a new interface to the `locator_bridge_node`:

`loc_server_interface_.reset(new LocatorRPCInterface(host, 8082));`

Please note [CONTRIBUTING.md](https://github.com/boschglobal/locator_ros_bridge/blob/noetic/CONTRIBUTING.md), and do not hesitate to ask in case of questions.

Btw, which ROS version are you using?

Best regards
Stefan

**Comment by robertwil** [comment]
Hi @slaible ,
while your vacation I've implemented the interface to the server to support listing server maps and exporting them as ROS maps (.png + .yaml for the map server package) which was the main reason for our interest in extending the bridge.
It is currently implemented as a separate node, which, in my opinion, makes sense as you don't always want/can connect to both the server and the client. 

We're using noetic.

Best regards
Robert

**Comment by slaible** [comment]
Hi @robertwil,
You are right, implementing it in a new node is a good approach. I am looking forward to your Pull Request. It will then always be kept compatible with the latest Locator version.

**Comment by robertwil** [comment]
@slaible Will close issue as PR is open
