### ISSUE TITLE
locator node dies after receiving an initial_pose

### ISSUE THREAD

**Issue by NikolasE** [boschglobal/locator_ros_bridge#29]
We have found an issue with setting the initial pose during startup. We regularly store the robot pose in a file to be able to use it to initialize the locator after a restart. This often works fine, but sometimes kills the node:
```

[recover_robot_pose-36] [INFO] [1668506589.712162746] [recover_robot_pose]: Sending initial pose to locator
[node-6] 
[node-6] terminate called after throwing an instance of 'Poco::JSON::JSONException'
[node-6]   what():  JSON Exception
[ERROR] [node-6]: process has died [pid 62601, exit code -6, cmd '/home/foo/ros2_overlay/install/bosch_locator_bridge/lib/bosch_locator_bridge/node --ros-args -r __node:=bridge_node --params-file /tmp/launch_params_4tlhu8cq'].
```
recover_robot_pose publishes on /initialpose and that kills the locator. The probability to kill the node is higher when we start the recover-node at the same time as the node, but that is not something we have debugged thoroughly. We have an older locator version so to use fix for the queue-bug, we are still running it out of an overlay.

**Comment by kfabian** [comment]
There was an issue that parallel JSON RPC calls could occur, e.g. when setting a config value while the periodic session refresh is happening. Since receiving a message on /initalpose also results in a JSON RPC call, your issue could be related. Does your fork already contain this commit 90bf3a587c6ed14a9337d23163a7461c63c0bb04 or could you try cherry-picking it to your fork?

**Comment by NikolasE** [comment]
Hello!

Thanks for the fast reply! We didn't have that commit yet, I'll pick it and test it. It occurred in around 20% of launches, so we should be able to quickly see if this fixes our problem. 

Could these fixes be also ported to the bridge-version for older locators?

**Comment by slaible** [comment]
Hello @NikolasE, for older Locator versions there are corresponding tags:
https://github.com/boschglobal/locator_ros_bridge/tree/main/bosch_locator_bridge#support-of-earlier-versions-of-rokit-locator

Newer bug fixes have to be cherry-picked then.

**Comment by NikolasE** [comment]
> Newer bug fixes have to be cherry-picked then.
Well, this is not really a solution. You don't get bug fixes by pulling the code, and you somehow have to look through the commits regularly to decide how to manually get these features into your code. (or how it likely happened just now, you experience and debug something that was already solved)

How about at least branching off at the tagged commits and cherry-pick the bug-fixes into these branches?

**Comment by kfabian** [comment]
Thanks for the feedback, we can understand the issue you have, when not using the latest Locator version. Nevertheless we actively maintain only the latest Locator version, since we also support multiple ROS distributions and we would otherwise end up with a matrix of version combinations to maintain. We could also create a new branch for the version you use, so that you can push back your fork.
A part from that, did applying the commit fix your issues, so that this issue can be closed?

**Comment by NikolasE** [comment]
Hey!
Yes, it worked. I spammed on /initialpose with 100Hz during startup and everyone survived :)

A new branch would be a good idea. I understand if not all new features are ported to older versions, but the two bugs (especially the queue-bug) make the bridge unusable, so I think it's important to get these fixes if you follow the install instructions.
