### ISSUE TITLE
Rokit Locator v1.4

### ISSUE THREAD

**Issue by motius-ggaryuk** [boschglobal/locator_ros_bridge#5]
Hello, 

is there an update to support Locator v1.4 planed. If yes, when can we expect it?

**Comment by slaible** [comment]
Hello @motius-ggaryuk,

Yes that is planned for the end of January next year. I will then let you know.
By the way, which ROS version are you using?

**Comment by motius-ggaryuk** [comment]
@slaible 

Thank you very much for the quick response. 
Is there an easy way for me to disable the version check in the bridge to at least be able to receive the pose? 
Or are the changes to the binary interface too big? - I was not supplied with the new api documentation yet. 
We are using ROS 1 noetic. 

I wish you a merry Christmas time :)

**Comment by slaible** [comment]
Hello @motius-ggaryuk,

There have been quite some changes since version 1.3. You could disable the version check here: https://github.com/boschglobal/locator_ros_bridge/blob/018570247c73c46b8a57ef3f57aedafe9a16388b/bosch_locator_bridge/src/locator_bridge_node.cpp#L84
And also disable setting the config here: https://github.com/boschglobal/locator_ros_bridge/blob/018570247c73c46b8a57ef3f57aedafe9a16388b/bosch_locator_bridge/src/locator_bridge_node.cpp#L388
Then you should be able to run the bridge, but I am not sure whether you will get the pose then.

For the API documentation feel free to contact the support: Robotics.Support@boschrexroth.de

**Comment by slaible** [comment]
Hello @motius-ggaryuk,

In principle, the bridge is now compatible with the new version, see this branch:
https://github.com/boschglobal/locator_ros_bridge/tree/update_to_version_1_4_noetic

Only the Dual Laser Feature is still missing. Once that is in, I will merge the branch and close this issue.

**Comment by motius-ggaryuk** [comment]
Hello @slaible, 
thanks for providing the update! 
Is it possible to launch the bridge without a scan topic? i.e.  use the settings made in aXessor and use the bridge only for odometry and localization.

**Comment by slaible** [comment]
Hello @motius-ggaryuk,

Yes, this is possible. Instead of `simple`, just specify the same laser type (e.g., `omron`, `sicklms`, etc.) as in the aXessor here:
https://github.com/boschglobal/locator_ros_bridge/blob/2edc878f5ebf4fdbc0ca5bf2764eaa13621392cd/bosch_locator_bridge/launch/bridge.launch#L49
Or comment out or delete the line to not change the aXessor setting at all.

**Comment by slaible** [comment]
The package `bosch_locator_bridge` has been updated to Locator version 1.4. Package releases so that you can install it with `apt install` will follow soon.
