### ISSUE TITLE
Build error in 2.1.9 branch main-v1.6 

### ISSUE THREAD

**Issue by Phymin** [boschglobal/locator_ros_bridge#50]
Please see the following screenshot for detail:
![859868d2844ea62d3fb9cb0c5318233](https://github.com/boschglobal/locator_ros_bridge/assets/9857420/8d5449c7-ff11-43b4-b475-b621488a65fd)

**Comment by kfabian** [comment]
There is no branch main-v1.6(you probably meant main-v1.4). Only the bridge versions for the latest locator versions are actively maintained. The main-v1.4 branch builds against ROS2 galactic, from the compile errors it looks like it is build against humble or newer. If you want to continue with main-v1.4 and ROS2 humble, you could simply try to cherry-pick this commit https://github.com/boschglobal/locator_ros_bridge/commit/0f797e1f868b03021040220f14a4d753d639b68c.

**Comment by Phymin** [comment]
Hi, 

I got this branch from your colleague HongKui Tang, you can checkout this branch with `git checkout 2.1.9 -b main-v1.6`, because he found that in v1.8, there is big delay of the localization with picoscan lidar, we also like to know when will this issue be fixed in v1.8? thanks

**Comment by thkfighter** [comment]
OS: Ubuntu 22.04
ROS Humble
Locator 1.6.4
LiDAR: picoScan150

According to [the last chapter of locator_ros_bridge/bosch_locator_bridge/README.md](https://github.com/boschglobal/locator_ros_bridge/tree/humble/bosch_locator_bridge#support-of-earlier-versions-of-rokit-locator) of latest commit (2a3363a9) of branch humble, 
> If you have version 1.6 of ROKIT Locator, checkout the corresponding tag:
>    git checkout 2.1.9 -b main-v1.6

With commit 8bf9a583, tag 2.1.9, there are some errors when building this package, all related to sub-package bosch_locator_bridge_utils, as shown in the picture posted by @Phymin on first floor. These errors have been fixed in a later commit, 8696169d.

My temporary solution:
```bash
git clone --branch=humble https://github.com/boschglobal/locator_ros_bridge.git
cd locator_ros_bridge
cp -r ./bosch_locator_bridge_utils <src_folder_of_your_ros2_ws>
git checkout 2.1.9 -b main-v1.6
cp -r ./bosch_locator_bridge <src_folder_of_your_ros2_ws>
```
A better solution is need.

**Comment by kfabian** [comment]
As mentioned in my first answer, the error when building version 2.1.9 with humble occurs because this version is compatible with galactic. As mentioned in the [changelog](https://github.com/boschglobal/locator_ros_bridge/blob/2a3363a9f65b81416480f7095ba5c109e6149460/bosch_locator_bridge_utils/CHANGELOG.rst?plain=1#L7) of the locator_bridge_utils the upgrade to humble was only made in version 2.1.10. Nevertheless the changes for humble are only minor and can be ported back by cherry picking commits https://github.com/boschglobal/locator_ros_bridge/commit/0f797e1f868b03021040220f14a4d753d639b68c and https://github.com/boschglobal/locator_ros_bridge/commit/545c902cc3e5f42707b096f11071ccfa56c02feb, e.g.
```bash
git cherry-pick 0f797e1 545c902
```
Also note that the locator_bridge_utils are only needed for Nav2 integration, if you don not need them you can just skip building them, e.g.
```bash
colcon build --packages-skip bosch_locator_bridge_utils
```

**Comment by kfabian** [comment]
@Phymin @thkfighter can this be closed?

**Comment by thkfighter** [comment]
> @Phymin @thkfighter can this be closed?

Yes. Please close it. @kfabian
